baseURL = "http://example.org/"
languageCode = "de-at"
title = "Kulturhofkeller Villach"
theme = "kulturhof-hugo"

[params]
  address = "Lederergasse 17, 9500 Villach"
  email = "office@kulturhofkeller.at"
  phone = "+43 699 15088177"

  [social]
    facebook = ""
    twitter = ""
    youtube = ""
    snapchat = ""
    instagram = ""
